### ISSUE TITLE
fix calendar coloring issue

### ISSUE THREAD

**Issue by yulheekim** [myidsan/humanCancerousInteraction#8]
- when milestone is edited, calendar shows wrong dates as 'active' (colored white)
- when end date is set outside of calendar range (February), nothing shows up as 'active'
- only show the selected weekdays as white ('active') on calendar

maybe get rid of the hard-coding for the calendar? and it will make everything else easier??

**Comment by myidsan** [comment]
1. Active issued resolved. 
2. This is not worth fixing since we don't have a calendar that would expand after Feb. I'll fix this after when that issue is resolved. 
3. This is fixed.

pushed and merged to master.
